from pprint import pprint
import os

import dotenv
import requests

dotenv.load_dotenv()

# OpenMetadata connection
OPENMETADATA_HOST_PORT = os.getenv('OPENMETADATA_HOST_PORT')
# Personal access token or ingestion-bot JWT (optional if API runs without auth)
OPENMETADATA_API_TOKEN = os.getenv('OPENMETADATA_API_TOKEN', '')

SCHEDULE_INTERVAL = os.getenv('SCHEDULE_INTERVAL', '0 * * * *')

# ClickHouse service definition
CLICKHOUSE_SERVICE_NAME = os.getenv('CLICKHOUSE_SERVICE_NAME')
CLICKHOUSE_SERVICE_DESCRIPTION = os.getenv('CLICKHOUSE_SERVICE_DESCRIPTION')
CLICKHOUSE_HOST_PORT = os.getenv('CLICKHOUSE_HOST_PORT')
CLICKHOUSE_USERNAME = os.getenv('CLICKHOUSE_USERNAME')
CLICKHOUSE_PASSWORD = os.getenv('CLICKHOUSE_PASSWORD')
CLICKHOUSE_DB_NAME = os.getenv('CLICKHOUSE_DB')
CLICKHOUSE_DATABASE_SCHEMA = os.getenv('CLICKHOUSE_DATABASE_SCHEMA')


#Фильтры
CLICKHOUSE_DB_INCLUDES = os.getenv('CLICKHOUSE_DB_INCLUDES', CLICKHOUSE_DB_NAME or '').split()
CLICKHOUSE_DB_EXCLUDES = os.getenv('CLICKHOUSE_DB_EXCLUDES', '').split()
CLICKHOUSE_SCHEMA_INCLUDES = os.getenv('CLICKHOUSE_SCHEMA_INCLUDES', '').split()
CLICKHOUSE_SCHEMA_EXCLUDES = os.getenv('CLICKHOUSE_SCHEMA_EXCLUDES', '').split()
CLICKHOUSE_TABLE_INCLUDES = os.getenv('CLICKHOUSE_TABLE_INCLUDES', '').split()
CLICKHOUSE_TABLE_EXCLUDES = os.getenv('CLICKHOUSE_TABLE_EXCLUDES', '').split()
CLICKHOUSE_USE_FQN_FILTERS = bool(os.getenv('CLICKHOUSE_USE_FQN_FILTERS', ''))
CLICKHOUSE_MARK_DELETED_TABLES = bool(os.getenv('CLICKHOUSE_MARK_DELETED_TABLES', ''))
CLICKHOUSE_MARK_DELETED_SCHEMAS = bool(os.getenv('CLICKHOUSE_MARK_DELETED_SCHEMAS', ''))
CLICKHOUSE_OVERRIDE_METADATA = bool(os.getenv('CLICKHOUSE_OVERRIDE_METADATA', ''))
